# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:    
  - stage: Dev
    displayName: Dev
    jobs:
      - job: plan
        pool:
          vmImage: ubuntu-latest
        displayName:  Terraform Dev Init and Apply
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'aws'
            command: 'init'
            backendServiceAWS: 'rcits-aws-1'
            backendAWSBucketName: 'rcits-terraform'
            backendAWSKey: 'ado-tf-test'
